const Permissions = {
    'MANAGE_DEPARTMENTS': 1,
    'MANAGE_JOB_VACANCIES': 2,
    'MANAGE_ROLES': 3,
    'MANAGE_ATTENDANCE': 4,
    'MANAGE_JOB_APPLICATIONS': 5,
    'MANAGE_EMPLOYEES': 6,
    'MANAGE_LOG': 7,
    'EXPORT_REPORTS': 8,
    'MANAGE_CONSULTANTS': 9,
    'MANAGE_CUSTOMERS': 10,
    'MANAGE_EVENTS': 11,
    'MANAGE_APPOINTMENTS': 12
};

export default Permissions;