export const GET_JOB_VACANCIES = 'GET_JOB_VACANCIES';
export const GET_JOB_VACANCIES_SUCCESS = 'GET_JOB_VACANCIES_SUCCESS';
export const GET_JOB_VACANCIES_FAILED = 'GET_JOB_VACANCIES_FAILED';

export const DELETE_JOB_VACANCY = 'DELETE_JOB_VACANCY';
export const DELETE_JOB_VACANCY_SUCCESS = 'DELETE_JOB_VACANCY_SUCCESS';
export const DELETE_JOB_VACANCY_FAILED = 'DELETE_JOB_VACANCY_FAILED';

export const UPDATE_JOB_VACANCY = 'UPDATE_JOB_VACANCY';
export const UPDATE_JOB_VACANCY_SUCCESS = 'UPDATE_JOB_VACANCY_SUCCESS';
export const UPDATE_JOB_VACANCY_FAILED = 'UPDATE_JOB_VACANCY_FAILED';

export const CREATE_JOB_VACANCY = 'CREATE_JOB_VACANCY';
export const CREATE_JOB_VACANCY_SUCCESS = 'CREATE_JOB_VACANCY_SUCCESS';
export const CREATE_JOB_VACANCY_FAILED = 'CREATE_JOB_VACANCY_FAILED';